name: Deploy App

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'sandbox'

env:
  AWS_REGION: ${{ vars.AWS_REGION || 'us-east-1' }}
  ECS_ENVIRONMENT: ${{ github.event.inputs.environment || (github.event_name == 'push' && github.ref == 'refs/heads/main' && 'prod') || 'sandbox' }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install app dependencies and run tests
        working-directory: app
        run: |
          npm install
          npm test

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker Image
        working-directory: app
        run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/devops-challenge-app:${{ github.sha }} .
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/devops-challenge-app:${{ github.sha }}
          docker tag ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/devops-challenge-app:${{ github.sha }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/devops-challenge-app:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/devops-challenge-app:latest

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster devops-challenge-${{ env.ECS_ENVIRONMENT }}-cluster --service devops-challenge-${{ env.ECS_ENVIRONMENT }}-app-service --force-new-deployment --region ${{ env.AWS_REGION }}