name: Sandbox Terraform Plan

on:
  push:
    branches:
      - "feature/**"

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: eu-north-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5


      - name: Terraform Init (VPC)
        working-directory: vpc
        run: |
          terraform init \
            -backend-config="bucket=fincra3-${{ secrets.AWS_ACCOUNT_ID }}-eu-north-1-tfstate" \
            -backend-config="dynamodb_table=fincra3-${{ secrets.AWS_ACCOUNT_ID }}-eu-north-1-lock-table" \
            -backend-config="key=vpc/terraform.tfstate"

      - name: Terraform Validate (VPC)
        working-directory: vpc
        run: terraform validate

      - name: Terraform Plan (VPC)
        working-directory: vpc
        run: terraform plan -var-file="../environment/sandbox.tfvars"

      - name: Terraform Init (Infra)
        working-directory: infra
        run: |
          terraform init \
            -backend-config="bucket=fincra3-${{ secrets.AWS_ACCOUNT_ID }}-eu-north-1-tfstate" \
            -backend-config="dynamodb_table=fincra3-${{ secrets.AWS_ACCOUNT_ID }}-eu-north-1-lock-table" \
            -backend-config="key=infra/terraform.tfstate"

      - name: Terraform Validate (Infra)
        working-directory: infra
        run: terraform validate

      - name: Terraform Plan (Infra)
        working-directory: infra
        run: terraform plan -var-file="../environment/sandbox.tfvars"
