name: VPC Terraform Plan

on:
  push:
    branches:
      - "feature/**"
    paths:
      - "vpc/**"
      - ".github/workflows/terraform-vpc-infra.yml"
  pull_request:
    branches:
      - "develop"
    paths:
      - "vpc/**"
      - ".github/workflows/terraform-vpc-infra.yml"


jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Terraform Operations
        uses: ./.github/actions/terraform-runs
        with:
          terraform_version: "~1.7.0"
          tfstate_file: vpc/terraform.tfstate
          tf_working_dir: vpc
          aws_oidc_role: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          terraform_action: plan
          environment: sandbox
          account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          region: eu-north-1
